version: "3.1"
services:
  db:
    image: postgres:13.2-alpine
    ports:
      - 4321:4321
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
  adminer:
    image: adminer
    ports:
      - 8090:8090
